<?xml version="1.0" encoding="utf-8"?><Database Name="SPTradeDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NF\SQLEXPRESS;Initial Catalog=SPTradeDB;Persist Security Info=True;User ID=sa" SettingsObjectName="ConsoleApplication5.Properties.Settings" SettingsPropertyName="SPTradeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admin">
    <Type Name="admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date_prefix" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="time_diff" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price_chart_url" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>